### ISSUE TITLE
Swapping tokens on uniswap/pancakeswap

### ISSUE THREAD

**Issue by adityawarmanfw** [joshstevens19/ethereum-multicall#12]
Hi, I'm looking for a way to swap tokens multiple times in a single transaction, like this [transaction](https://bscscan.com/tx/0xa78af203d1c0828adfa3d73003a47e6ba946fb1deb3ebf5d44144d85b29b1942).

Do you think it's achievable using Multicall?

**Comment by joshstevens19** [comment]
Hey thanks for this issue. No this library only does const contract calls it doesn’t support signing transaction calls. To do what you want you have to find a contract like the above which supports doing this. 👍
