### ISSUE TITLE
use custom contract address

### ISSUE THREAD

**Issue by Lsw931102** [joshstevens19/ethereum-multicall#19]
I want to use the contract that I deploy on okexchain, but there is something wrong:
![image](https://user-images.githubusercontent.com/13031383/137097709-e7b7f411-b01a-4c0e-906d-489029f53b88.png)
if I open the 'tryAggregate'
![image](https://user-images.githubusercontent.com/13031383/137097947-6d7b642d-98c2-4c67-a949-010f6a7f02ba.png)
if turn off 'tryAggregate', I can get a result,bug the balance of token is wrong
![image](https://user-images.githubusercontent.com/13031383/137098157-acdf7991-3b7d-4651-b8f1-cbebbcdb8ebc.png)
![image](https://user-images.githubusercontent.com/13031383/137098194-aed7c7a6-59d1-416d-8949-3550606a2d29.png)

can u tell me how can use a custom contract?

**Comment by heyitaki** [comment]
@joshstevens19 any idea why the returnValues field in the screenshot above doesn't have a name field corresponding to the ABI? I'm encountering this locally as well.

**Comment by joshstevens19** [comment]
@heyitaki its always the same order the ABI output is defined as.. we don’t expose those details on the return value as this is the contract return data, as said it will always be the order the ABI is defined so easy for project by project to know which is which.

**Comment by joshstevens19** [comment]
Closing as no repo has been given will open if one is given.
