### ISSUE TITLE
'Cannot read properties of undefined' while call

### ISSUE THREAD

**Issue by DumplingsHunter** [joshstevens19/ethereum-multicall#21]
I have parts of code:

`this.multicall = new ethereumMulticall
      .Multicall({ nodeUrl: config.rpc, tryAggregate: true });`
or
`this.multicall = new ethereumMulticall
      .Multicall({ ethersProvider: connect.provider, tryAggregate: true });`

and

`   let answ = await this.multicall.call({});`
or
`   answ = await this.multicall.call(multicallContext);`

All combinations (with empty context too) executing gives same error:
`
/node_modules/ethereum-multicall/node_modules/@ethersproject/abi/lib/interface.js:101
        properties_1.defineReadOnly(this, "fragments", abi.map(function (fragment) {
                                                           ^

TypeError: Cannot read properties of undefined (reading 'map')

`

**Comment by DumplingsHunter** [comment]
Where's the root and how can I handle this?

**Comment by DumplingsHunter** [comment]
It was wrong context structure in both case, this is the point. In second case with `answ = await this.multicall.call(multicallContext);` was wrong context struct too -- I was pushed context arrays to multicallContext. Solution in a simply concat, not a pushing

**Comment by joshstevens19** [comment]
Hey all sorted then.. was just bad mapping your end? Glad your sorted! Here to help if you need anything else! 👍👍
