### ISSUE TITLE
Network info should be cached for performance

### ISSUE THREAD

**Issue by lljxx1** [joshstevens19/ethereum-multicall#22]
https://github.com/joshstevens19/ethereum-multicall/blob/master/src/multicall.ts#L404

**Comment by lljxx1** [comment]
should use `StaticJsonProvider`

**Comment by joshstevens19** [comment]
Did you mean to close this @lljxx1 im away till 22nd this is why I can’t look at this right now.. happy for these suggestions.. if you reopen can look when back from holiday! 👍

**Comment by lljxx1** [comment]
> Did you mean to close this @lljxx1 im away till 22nd this is why I can’t look at this right now.. happy for these suggestions.. if you reopen can look when back from holiday! 👍

happy holiday lol！
I realize using `ethers.providers.StaticJsonProvider` can slove this problem.
