### ISSUE TITLE
swapExactETHForTokens transaction

### ISSUE THREAD

**Issue by Malvaphe** [joshstevens19/ethereum-multicall#27]
How can I convert the following transaction to work in a multicall?

var contract = new web3.eth.Contract(routerAbi, routerAddress);
var swapETHforTokens = contract.methods.swapExactETHForTokens(0, [WBNB, tokenAddress], WalletAddress, timeStamp);
var encodedABI = swapETHforTokens.encodeABI();
var swapETHforTokensTX = {
   from: WalletAddress,
   to: routerAddress,
   gas: 176024,
   data: encodedABI,
   value: web3.utils.toWei(ETHtoSell, 'ether'),
};

No problem calling it with eth.call:

await web3.eth
   .call(swapETHforTokenstx, 'pending')
   .then((result) => {
      console.log(web3.eth.abi.decodeLog([{ 'internalType': 'uint256[]', 'name': 'amounts', 'type': 'uint256[]' }], result).amounts[1]);
   })
   .catch((revertReason) => console.log(revertReason));

**Comment by Malvaphe** [comment]
The problem is in the contract, which does not make it possible to do what is requested. To make this type of request it is necessary to modify the contract:
```
function aggregate(Call[] memory calls) public returns (uint256 blockNumber, bytes[] memory returnData) {
        blockNumber = block.number;
        returnData = new bytes[](calls.length);
        bytes memory ris = hex"00";
        for(uint256 i = 0; i < calls.length; i++) {
            (bool success, bytes memory ret) = calls[i].target.call{value: calls[i].ethtosell, gas: calls[i].gastouse}(calls[i].callData);
            if (!success){
                ret = ris;
            }
            returnData[i] = ret;
        }
    }
```
It is also necessary to add some features to the contract, namely the ability to receive BNB (to pay the fees).
`receive() external payable{}`
Now it is possible to fulfill the request:
```
import Web3 from 'web3';
var web3 = new Web3('speedy node...');

const routerAbi = [];
const multicallAbi = [];
var MAINTOKEN = 'main token address (WETH, WBNB ...)';
var tokenAddress = '...';
var multicallAddress = '...';
var timeStamp = web3.utils.toHex(Math.round(Date.now() / 1000) + 60 * 20);
var maxgas = 2000000;

var routerContract = new web3.eth.Contract(routerAbi, routerAddress);
var multicallContract = new web3.eth.Contract(multicallAbi, multicallAddress);

var swapETHforTokens = routerContract.methods.swapExactETHForTokens(0, [MAINTOKEN, tokenAddress], multicallAddress, timeStamp);
var encodedABI = swapETHforTokens.encodeABI();

var MAINTOKENtoSell = 100000000000000;
var result = await multicallContract.methods
   .aggregate([{ target: routerAddress, callData: encodedABI, ethtosell: MAINTOKENtoSell, gastouse: maxgas }])
   .call()
   .catch((err) => console.log(err));
console.log(result);
```

**Comment by Marijus** [comment]
@malvaphe - is it possible to use multicall to call swapExactETHForTokens without actually paying gas and swapping the tokens?

I'm looking to use multicall to test on chain whether I can swapExactETHForTokens successfully and swap it back before actually submitting the transactions.

I know websites like https://honeypot.is/ do this on chain, however, I'm wondering if they're using technique such as a multicall.
