### ISSUE TITLE
Using Multicall with ethers Wallet

### ISSUE THREAD

**Issue by rootkitfinancedev** [joshstevens19/ethereum-multicall#28]
Hi,

The comment in the code snippet says that 

> ...ethers hold providers in other context like wallet, signer etc all can be passed in as well.

So, I assumed that the following code is correct
```
const provider = new ethers.providers.JsonRpcProvider(process.env.NETWORK_URL);
const wallet = new ethers.Wallet(process.env.ACCOUNT).connect(provider);
const multicall = new ethereumMulticall.Multicall({ ethersProvider: wallet , tryAggregate: true });
```

But I'm, getting

> UnhandledPromiseRejectionWarning: TypeError: ethersProvider.getNetwork is not a function

What am I missing? How can use Multicall with Wallet?

Thank you

**Comment by joshstevens19** [comment]
Hey you need to pass in the provider not the wallet! 

const multicall = new ethereumMulticall.Multicall({ ethersProvider: provider , tryAggregate: true });

Then it should work for you

**Comment by rootkitfinancedev** [comment]
Thanks, I tried that, it works, but how I specify the account/signer that executes the call in this case?
I need to call a function that's only available for certain accounts (e.g. onlyOwner)

**Comment by joshstevens19** [comment]
This library only does constant calls aka read only calls it doesn’t do signing calls! 👍

**Comment by mburger81** [comment]
@joshstevens19 is there a way to support signing calls?

In the README there is mentioned that we could pass as well signer.

What I'm even not sure, is this limit just on you lib or does a MULTICALL contract NOT supporting signed calls.
Im not sure if multicall contract is supporting those functionality
