### ISSUE TITLE
Add python usage examples  

### ISSUE THREAD

**Issue by Buco11-dev** [joshstevens19/ethereum-multicall#30]
Nice work! Thanks for sharing with everyone. Any chance you could add python usage examples to the list of languages on the main page? Please consider that for the py family. Thanks again.

**Comment by joshstevens19** [comment]
Hey this is a typescript lib and doesn’t support python right now. The contracts it used could be written in python to support python apps. 

https://github.com/banteg/multicall.py < this does what you want in python I think?

**Comment by Buco11-dev** [comment]
Oh, I see. I appreciate your feedback. Thank you!

Thanks again for the reference, it's exactly what I was looking for.
