### ISSUE TITLE
tryAggregate fails when there's an error decoding.

### ISSUE THREAD

**Issue by chidev** [joshstevens19/ethereum-multicall#31]
I'm trying to get a list of tokens for a user's wallet, and there's a contract that is likely malformed. The blockchain call works, but when multicall tries to decode with the ABI (symbol, balanceOf, name, decimals, totalSupply) it fails w/ a data out of bounds error:
`Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.5.0)`

If we just wrapped the ABI decode portion of multicall.js with a try/catch, we could still get the expected behavior of aggregation despite what happens during calls to the network _and_ decoding.

Here's the token (it's a Uniswap v2 LP token):
https://etherscan.io/token/0xfb072e4dE3719E84503b3fB303173Dd6D29aB472#readContract

When I call the same methods manually they work

**Comment by joshstevens19** [comment]
Yoo sorry been on holiday and thanks for rains the issue… can you dump a working example here so I can quickly recreate without constructing myself. A general try catch on the decode probably won’t make sense for every situation so before I do anything like that would like to test the way it fails out.

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/ethereum-multicall/pull/32

**Comment by joshstevens19** [comment]
will be deployed later today
