### ISSUE TITLE
Block-Specific Multicall

### ISSUE THREAD

**Issue by Ncookiez** [joshstevens19/ethereum-multicall#37]
Is it possible to pass a block parameter to the multicall in order to execute queries at that specific block height?

In Ethers, a single query can be executed with a blocktag (`{ blockTag: blockNumber }`) in order to accomplish this.

Having similar functionality on multicalls would be incredible.

**Comment by jsertx** [comment]
I have created this PR to do this as I needed it too.
https://github.com/joshstevens19/ethereum-multicall/pull/39

**Comment by joshstevens19** [comment]
Merged above will deploy tomorrow! 👏👏
