### ISSUE TITLE
Only one result is returned if multiple items returned from contract method

### ISSUE THREAD

**Issue by cdljsj** [joshstevens19/ethereum-multicall#4]
Take below method for example, it returns 3 uint, but I can only get one from returnValues
    function getAccountLiquidity(address account) public view returns (uint, uint, uint) {
    }

**Comment by joshstevens19** [comment]
Hey can you give me a working index.js / index.ts file so I can test this out with your example code please

**Comment by mashup-purveyor** [comment]
FWIW I have also found this issue to happen. Requesting from [this contract](https://bscscan.com/address/0x4076CC26EFeE47825917D0feC3A79d0bB9a6bB5c#readContract), for example, claimableRewards returns an array of length two with the required values, however chaining in another call to withdrawableBalance returns one bignumber and lockedBalances the same, when they should be returning more values.

**Comment by mashup-purveyor** [comment]
Here's an example, check the comments in the index.js for what is not returning properly. I grabbed a random address for that, if it doesn't return results at all when you try, you should be able to grab one from [here](https://bscscan.com/address/0x4076CC26EFeE47825917D0feC3A79d0bB9a6bB5c).
[multicall example.zip](https://github.com/joshstevens19/ethereum-multicall/files/6410900/multicall.example.zip)

**Comment by joshstevens19** [comment]
Hey, thanks a lot for the example this helped me track down the issue.

It should be fixed in version 2.1.1 which I have just published! 

Let me know if it's working for you now.

**Comment by mashup-purveyor** [comment]
Going to check, I just sat down to code around this, thanks for the quick work!

**Comment by mashup-purveyor** [comment]
Thanks a million @joshstevens19!! Appreciate the effort on a Sunday, saved me coding around this.

**Comment by joshstevens19** [comment]
Hey @mashup-purveyor no worries thanks for giving me an example! Glad we sorted it. Let me know if you get anymore issues.
