### ISSUE TITLE
Multicall do not run in BSC TESTNET

### ISSUE THREAD

**Issue by phamhongphuc1999** [joshstevens19/ethereum-multicall#44]
- I use muticall to call in bsc testnet with web3js but it cause a error `Error: Returned error: execution reverted`.
- I am sure my contract address and ABI is correct because I am able to call this contract without muticall.

Could anyone tell me if I missed anything?

**Comment by joshstevens19** [comment]
hey please post example

**Comment by joshstevens19** [comment]
deployed new bsc testnet contract let me know if fixed closing for now
