### ISSUE TITLE
feature request: upgrade to Multicall3

### ISSUE THREAD

**Issue by mds1** [joshstevens19/ethereum-multicall#45]
Looks like you currently maintain a hardcoded mapping of networks to addresses, and need to deploy a new contract and update that for each chain users want supported. If you migrate to [Multicall3](https://github.com/mds1/multicall) you'll support more chains with less maintenance (I'm biased of course, but I do think it'll be easier for you).

It's fully backwards compatible, and adds a few new methods to offer users more granularity over reverting calls.

Looks like etherlite is the only chain Multicall3 isn't deployed on that this lib currently supports: if people actually use that and you need to maintain compatibility, we just need someone to fund to the Multicall3 deployer account (0x05f32B3cC3888453ff71B01135B34FF8e41263F2) and I can deploy it on that chain.

**Comment by joshstevens19** [comment]
Hey man! Thanks for raising this - for sure would love to upgrade happy if you wanted to do a PR (should be very easy) if not il add it to my todo list and get it done for us! Would love to support multicall3 for everything and we can try to sort etherlite but for now that using v2 is fine IMO!
