### ISSUE TITLE
Uncaught (in promise) Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.1.2) 

### ISSUE THREAD

**Issue by billyriantono** [joshstevens19/ethereum-multicall#5]
Hello try to using it on browser via vue.js but  got error : 
index.js?ffb2:166 Uncaught (in promise) Error: network does not support ENS (operation="ENS", network="unknown", code=UNSUPPORTED_OPERATION, version=providers/5.1.2)
    at Logger.makeError (index.js?ffb2:166)
    at Logger.throwError (index.js?ffb2:175)
    at JsonRpcProvider.eval (base-provider.js?bc79:1244)
    at Generator.next (<anonymous>)
    at fulfilled (base-provider.js?bc79:5)
   
Is it because doesnt support on browser ? 

here is my initialization : 
```
const ethersProvider = new providers.getDefaultProvider('https://bsc-dataseed1.binance.org');
    const multicall = new Multicall({ ethersProvider: ethersProvider, multicallCustomContractAddress: '0x1Ee38d535d541c55C9dae27B12edf090C608E6Fb' });
```

**Comment by joshstevens19** [comment]
hey, that error seems it's from ethers, not us. It works fine in browsers. 

If you create a github repo i can investigate what is causing your issue. Multicall works on any browser, any framework! :+1:

**Comment by billyriantono** [comment]
Thanks for the information yes,seems its error from ether.js :D

**Comment by joshstevens19** [comment]
Great any further help give me a shout.
