### ISSUE TITLE
Accessing Multicall3 Contract Methods

### ISSUE THREAD

**Issue by bbjansen** [joshstevens19/ethereum-multicall#55]
I am trying to access the build in multicall3 method getCurrentBlockTimestamp() using the following ABI

```json
[
      {      
        inputs: [],
        name: "getCurrentBlockTimestamp",
        outputs: [
          {
            internalType: "uint256",
            name: "",
            type: "uint256"
          }
        ],
        stateMutability: "view",
        type: "function"
      }
  ]
```

with the following call in my contractCallContext

```json
             { reference: 'blockTime', methodName: 'getCurrentBlockTimestamp', methodParameters: null }
```

Unfortunately I get the error:

```
rror: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall3: call failed" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="aggregate((address,bytes)[])", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000174d756c746963616c6c333a2063616c6c206661696c6564000000000000000000", errorArgs=["Multicall3: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall3: call failed", code=CALL_EXCEPTION, version=abi/5.7.0)
```

How can I access the build in multicall contract methods? I cannot find anything in the readme

**Comment by bbjansen** [comment]
fixed it by simply using a separate call context object with the the multicall3 address and the call. apparently you cannot mix the global methods with other methods from different contract addresses like in the original multicall-js package.

**Comment by joshstevens19** [comment]
Hey thanks for the issue, can you show me an example of the working one and not working one so I can assess if this is something we should fix here or not
