### ISSUE TITLE
Multicall fails on Arbitrum for most RPCs

### ISSUE THREAD

**Issue by BenAzlay** [joshstevens19/ethereum-multicall#57]
When I try to perform a multicall on Arbitrum, most RPCs will return this error:
`console.error("getUniswapV3PairPrice ERROR", networkId, e)`
The only RPC I've tried that does work on Arbitrum is: https://arb1.arbitrum.io/rpc
On other networks (I tried mainnet, Optimism and Goerli) the multicalls work perfectly.

I create my multicall instances like this:
`const multicall = new Multicall({ web3Instance: web3, tryAggregate: true });`
With web3 here being new Web3(myRpcUrl). I have also tried using `nodeUrl: myRpcUrl` instead of web3Instance, to no avail.

**Comment by Zen-Maxi** [comment]
Bumping this with the same problem. Any progress on this? I am also having issues with nothing returning for my arbitrum calls, but all other networks are fine without issue. The rpc mentioned works, but when it is down nothing else can fill in.

**Comment by joshstevens19** [comment]
This is still an issue ? - i can not see how the lib itself can have an issue because it works on the standard multicall response type and its the same contract deployed - if its still an issue i can have a look and see if they return a different  response - have you got any error logs?
