### ISSUE TITLE
Ethereum wallet for donate

### ISSUE THREAD

**Issue by citizenofneo** [joshstevens19/ethereum-multicall#7]
Public pls your ETH wallet. Good way for donate. 
You doing perfectly work, and save time of developers:)

**Comment by joshstevens19** [comment]
Hey, @citizenofneo good idea! I have added the thanks and support in the readme now and created a new eth address for open-source sponsors. 

If this package did help feel free to donate > `0x699c2daD091ffcF18f3cd9E8495929CA3a64dFe1` 

Thanks a lot for your support and kind words!
