### ISSUE TITLE
Multicall2 (tryAggregate) missing from Matic

### ISSUE THREAD

**Issue by razgraf** [joshstevens19/ethereum-multicall#8]
It seems that the variant that allows for failing calls wasn't yet deployed to Matic/Mumbai. The official [maker](https://github.com/makerdao/multicall) repo doesn't include addresses for Multicall2 and the file with configurations in the library unfortunately [mixes](https://github.com/joshstevens19/ethereum-multicall/blob/master/src/multicall.ts) the usage of v1 and v2.

As a heads up for anyone using the aggregate variant, don't forget to manually reference a multicall2 contract in the constructor. If you want to use something already deployed, I've added them on Matic and Mumbai if anyone wants to use them there:

Matic: `0x275617327c958bd06b5d6b871e7f491d76113dd8`
Mumbai: `0xe9939e7Ea7D7fb619Ac57f648Da7B1D425832631`

P.S. Great work with the library, was really useful!

**Comment by joshstevens19** [comment]
Hey! Great thanks a lot for this. Il update the library tomorrow to have those as the contract addresses for those networks. Huge thanks for letting me know and raising this issue. 

PR obviously welcome it’s as simple change: 

https://github.com/joshstevens19/ethereum-multicall/blob/master/src/multicall.ts#L500 < here and then in readme. If not il do it tomorrow! Thanks again

**Comment by joshstevens19** [comment]
That is now released at 2.5.1 thanks again for the PR
