### ISSUE TITLE
Built-in support for Oasis Sapphire

### ISSUE THREAD

**Issue by whatl3y** [joshstevens19/ethereum-multicall#85]
Would be great to add a multicall contract and support natively from this library for [Oasis Sapphire](https://oasisprotocol.org/sapphire)

Chain ID: `23294`
RPC: https://sapphire.oasis.io
Explorer: https://explorer.sapphire.oasis.io/

**Comment by joshstevens19** [comment]
PR welcome

**Comment by whatl3y** [comment]
https://github.com/joshstevens19/ethereum-multicall/pull/90

**Comment by joshstevens19** [comment]
https://github.com/joshstevens19/ethereum-multicall/releases/tag/2.23.0
